services:
  qa-bot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
      - /app/.git
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=auto
    stdin_open: true
    tty: true